spring:
  application:
    name: account-management-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:account-management
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


address:
  lookup:
    baseurl: https://api.zippopotam.us/

developer:
  name: Gaurav Kumar
  email: gaurav.mute@gmail.com
  webUrl: https://github.com/gauravnewton